export default {
  COUCHDB_USER: "couchusername",
  COUCHDB_PASS: "couchpassword",
  COUCHDB_SECRET: "couchsecret",
  SESSION_SECRET: "somesecret",
  PRIVATE_KEY: { "keydata": "somedata" },
  MAILGUN_API_KEY: "your-mailgun-api-key",
  MAILGUN_DOMAIN: "mailer.somedomain.com",
  MAILERLITE_API_KEY: "123123123123123",
  SUPPORT_EMAIL: "support@somedomain.com",
  SUPPORT_URGENT_EMAIL: "urgent@somedomain.com",
  URGENT_MESSAGE_SUBJECT: "Urgent message received",
  URGENT_MESSAGE_BODY: "Hi,<br><br>This auto-reply is to confirm that we got your urgent message.<br>Your message will appear as a notification and a text message on the developer's phone, which they'll see right away (if they're awake).<br><br>If you have anything else to add that might help us resolve your issue, just reply to this.<br>Is your problem related to one of your documents, or all of them?<br>Does it occur on one of your devices, or all of them?<br>Do you grant us permission to access your account?<br>Anything you can think of, please let us know.<br><br>We're sorry you're having trouble... we'll do our best to help!<br>The Gingko Team",
  NTFY_URL: "https://ntfy.sh/my_topic",
  STRIPE_SECRET_KEY: "sk_test_123412341234",
  URL_ROOT: "https://app.example.com",
  ANTHROPIC_API_KEY: "1234123412344",
};
